version: "3.9"

services:
  web:
    build: .
    ports:
      - "8080:8080"
  tester:
    image: peterevans/vegeta
    entrypoint: "echo 'GET http://localhost:8080/messages' | vegeta attack -rate=10 -duration=30s | tee results.bin | vegeta report"
    restart: "no"